/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProjectEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "APPROVAL_THRESHOLD"
      | "APPROVER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MANAGER_ROLE"
      | "MAX_PLATFORM_FEE"
      | "REFUND_TIMELOCK"
      | "REQUIRED_APPROVALS"
      | "UPGRADER_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "allocateTask"
      | "approvePayment"
      | "cancelProject"
      | "cancelTask"
      | "completeTask"
      | "finToken"
      | "fundProject"
      | "getPlatformFeeAmount"
      | "getProject"
      | "getRoleAdmin"
      | "getTask"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "pause"
      | "paused"
      | "platformFeePercentage"
      | "platformFeeRecipient"
      | "processRefund"
      | "projectCounter"
      | "projects"
      | "proxiableUUID"
      | "renounceRole"
      | "requestRefund"
      | "revokeRole"
      | "setPlatformFee"
      | "setPlatformFeeRecipient"
      | "supportsInterface"
      | "taskCounter"
      | "tasks"
      | "unpause"
      | "updateTaskHashrate"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HashrateUpdated"
      | "Initialized"
      | "Paused"
      | "PaymentApproved"
      | "PaymentReleased"
      | "PlatformFeeCollected"
      | "ProjectCancelled"
      | "ProjectFunded"
      | "RefundProcessed"
      | "RefundRequested"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TaskAllocated"
      | "TaskCompleted"
      | "TaskStatusUpdated"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "APPROVAL_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "APPROVER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFUND_TIMELOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REQUIRED_APPROVALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allocateTask",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "finToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformFeeAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "taskCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTaskHashrate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "APPROVAL_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "APPROVER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFUND_TIMELOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REQUIRED_APPROVALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformFeeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTaskHashrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace HashrateUpdatedEvent {
  export type InputTuple = [taskId: BigNumberish, hashrate: BigNumberish];
  export type OutputTuple = [taskId: bigint, hashrate: bigint];
  export interface OutputObject {
    taskId: bigint;
    hashrate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentApprovedEvent {
  export type InputTuple = [taskId: BigNumberish, approver: AddressLike];
  export type OutputTuple = [taskId: bigint, approver: string];
  export interface OutputObject {
    taskId: bigint;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, worker: string, amount: bigint];
  export interface OutputObject {
    taskId: bigint;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeCollectedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    recipient: AddressLike,
    feeAmount: BigNumberish,
    workerAmount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    recipient: string,
    feeAmount: bigint,
    workerAmount: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    recipient: string;
    feeAmount: bigint;
    workerAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCancelledEvent {
  export type InputTuple = [projectId: BigNumberish, employer: AddressLike];
  export type OutputTuple = [projectId: bigint, employer: string];
  export interface OutputObject {
    projectId: bigint;
    employer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectFundedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    employer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    employer: string,
    amount: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    employer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundProcessedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    employer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    employer: string,
    amount: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    employer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundRequestedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    employer: AddressLike,
    requestedAt: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    employer: string,
    requestedAt: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    employer: string;
    requestedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAllocatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    projectId: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    projectId: bigint,
    worker: string,
    amount: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    projectId: bigint;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [taskId: BigNumberish, worker: AddressLike];
  export type OutputTuple = [taskId: bigint, worker: string];
  export interface OutputObject {
    taskId: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskStatusUpdatedEvent {
  export type InputTuple = [taskId: BigNumberish, status: BigNumberish];
  export type OutputTuple = [taskId: bigint, status: bigint];
  export interface OutputObject {
    taskId: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProjectEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ProjectEscrow;
  waitForDeployment(): Promise<this>;

  interface: ProjectEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  APPROVAL_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  APPROVER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  REFUND_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  REQUIRED_APPROVALS: TypedContractMethod<[], [bigint], "view">;

  UPGRADER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  allocateTask: TypedContractMethod<
    [projectId: BigNumberish, worker: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  approvePayment: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelProject: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  completeTask: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  finToken: TypedContractMethod<[], [string], "view">;

  fundProject: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getPlatformFeeAmount: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  getProject: TypedContractMethod<
    [projectId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        employer: string;
        totalFunded: bigint;
        totalAllocated: bigint;
        totalReleased: bigint;
        status: bigint;
        createdAt: bigint;
        refundRequestedAt: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        projectId: bigint;
        worker: string;
        amount: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        approvalCount: bigint;
        hashrate: bigint;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [_finToken: AddressLike, admin: AddressLike],
    [void],
    "nonpayable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFeePercentage: TypedContractMethod<[], [bigint], "view">;

  platformFeeRecipient: TypedContractMethod<[], [string], "view">;

  processRefund: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  projectCounter: TypedContractMethod<[], [bigint], "view">;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        employer: string;
        totalFunded: bigint;
        totalAllocated: bigint;
        totalReleased: bigint;
        status: bigint;
        createdAt: bigint;
        refundRequestedAt: bigint;
      }
    ],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestRefund: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<[arg0: BigNumberish], [void], "view">;

  setPlatformFeeRecipient: TypedContractMethod<
    [arg0: AddressLike],
    [void],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  taskCounter: TypedContractMethod<[], [bigint], "view">;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        projectId: bigint;
        worker: string;
        amount: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        approvalCount: bigint;
        hashrate: bigint;
      }
    ],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateTaskHashrate: TypedContractMethod<
    [taskId: BigNumberish, newHashrate: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "APPROVAL_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "APPROVER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFUND_TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REQUIRED_APPROVALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allocateTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, worker: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvePayment"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelProject"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundProject"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getPlatformFeeAmount"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProject"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        employer: string;
        totalFunded: bigint;
        totalAllocated: bigint;
        totalReleased: bigint;
        status: bigint;
        createdAt: bigint;
        refundRequestedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        projectId: bigint;
        worker: string;
        amount: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        approvalCount: bigint;
        hashrate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_finToken: AddressLike, admin: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processRefund"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "projectCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        employer: string;
        totalFunded: bigint;
        totalAllocated: bigint;
        totalReleased: bigint;
        status: bigint;
        createdAt: bigint;
        refundRequestedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRefund"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[arg0: BigNumberish], [void], "view">;
  getFunction(
    nameOrSignature: "setPlatformFeeRecipient"
  ): TypedContractMethod<[arg0: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "taskCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        projectId: bigint;
        worker: string;
        amount: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        approvalCount: bigint;
        hashrate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTaskHashrate"
  ): TypedContractMethod<
    [taskId: BigNumberish, newHashrate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "HashrateUpdated"
  ): TypedContractEvent<
    HashrateUpdatedEvent.InputTuple,
    HashrateUpdatedEvent.OutputTuple,
    HashrateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentApproved"
  ): TypedContractEvent<
    PaymentApprovedEvent.InputTuple,
    PaymentApprovedEvent.OutputTuple,
    PaymentApprovedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeCollected"
  ): TypedContractEvent<
    PlatformFeeCollectedEvent.InputTuple,
    PlatformFeeCollectedEvent.OutputTuple,
    PlatformFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCancelled"
  ): TypedContractEvent<
    ProjectCancelledEvent.InputTuple,
    ProjectCancelledEvent.OutputTuple,
    ProjectCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ProjectFunded"
  ): TypedContractEvent<
    ProjectFundedEvent.InputTuple,
    ProjectFundedEvent.OutputTuple,
    ProjectFundedEvent.OutputObject
  >;
  getEvent(
    key: "RefundProcessed"
  ): TypedContractEvent<
    RefundProcessedEvent.InputTuple,
    RefundProcessedEvent.OutputTuple,
    RefundProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RefundRequested"
  ): TypedContractEvent<
    RefundRequestedEvent.InputTuple,
    RefundRequestedEvent.OutputTuple,
    RefundRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAllocated"
  ): TypedContractEvent<
    TaskAllocatedEvent.InputTuple,
    TaskAllocatedEvent.OutputTuple,
    TaskAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskStatusUpdated"
  ): TypedContractEvent<
    TaskStatusUpdatedEvent.InputTuple,
    TaskStatusUpdatedEvent.OutputTuple,
    TaskStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "HashrateUpdated(uint256,uint256)": TypedContractEvent<
      HashrateUpdatedEvent.InputTuple,
      HashrateUpdatedEvent.OutputTuple,
      HashrateUpdatedEvent.OutputObject
    >;
    HashrateUpdated: TypedContractEvent<
      HashrateUpdatedEvent.InputTuple,
      HashrateUpdatedEvent.OutputTuple,
      HashrateUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentApproved(uint256,address)": TypedContractEvent<
      PaymentApprovedEvent.InputTuple,
      PaymentApprovedEvent.OutputTuple,
      PaymentApprovedEvent.OutputObject
    >;
    PaymentApproved: TypedContractEvent<
      PaymentApprovedEvent.InputTuple,
      PaymentApprovedEvent.OutputTuple,
      PaymentApprovedEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "PlatformFeeCollected(uint256,address,uint256,uint256)": TypedContractEvent<
      PlatformFeeCollectedEvent.InputTuple,
      PlatformFeeCollectedEvent.OutputTuple,
      PlatformFeeCollectedEvent.OutputObject
    >;
    PlatformFeeCollected: TypedContractEvent<
      PlatformFeeCollectedEvent.InputTuple,
      PlatformFeeCollectedEvent.OutputTuple,
      PlatformFeeCollectedEvent.OutputObject
    >;

    "ProjectCancelled(uint256,address)": TypedContractEvent<
      ProjectCancelledEvent.InputTuple,
      ProjectCancelledEvent.OutputTuple,
      ProjectCancelledEvent.OutputObject
    >;
    ProjectCancelled: TypedContractEvent<
      ProjectCancelledEvent.InputTuple,
      ProjectCancelledEvent.OutputTuple,
      ProjectCancelledEvent.OutputObject
    >;

    "ProjectFunded(uint256,address,uint256)": TypedContractEvent<
      ProjectFundedEvent.InputTuple,
      ProjectFundedEvent.OutputTuple,
      ProjectFundedEvent.OutputObject
    >;
    ProjectFunded: TypedContractEvent<
      ProjectFundedEvent.InputTuple,
      ProjectFundedEvent.OutputTuple,
      ProjectFundedEvent.OutputObject
    >;

    "RefundProcessed(uint256,address,uint256)": TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;
    RefundProcessed: TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;

    "RefundRequested(uint256,address,uint256)": TypedContractEvent<
      RefundRequestedEvent.InputTuple,
      RefundRequestedEvent.OutputTuple,
      RefundRequestedEvent.OutputObject
    >;
    RefundRequested: TypedContractEvent<
      RefundRequestedEvent.InputTuple,
      RefundRequestedEvent.OutputTuple,
      RefundRequestedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TaskAllocated(uint256,uint256,address,uint256)": TypedContractEvent<
      TaskAllocatedEvent.InputTuple,
      TaskAllocatedEvent.OutputTuple,
      TaskAllocatedEvent.OutputObject
    >;
    TaskAllocated: TypedContractEvent<
      TaskAllocatedEvent.InputTuple,
      TaskAllocatedEvent.OutputTuple,
      TaskAllocatedEvent.OutputObject
    >;

    "TaskCompleted(uint256,address)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskStatusUpdated(uint256,uint8)": TypedContractEvent<
      TaskStatusUpdatedEvent.InputTuple,
      TaskStatusUpdatedEvent.OutputTuple,
      TaskStatusUpdatedEvent.OutputObject
    >;
    TaskStatusUpdated: TypedContractEvent<
      TaskStatusUpdatedEvent.InputTuple,
      TaskStatusUpdatedEvent.OutputTuple,
      TaskStatusUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
